"""Generate analysis reports."""

from typing import Dict
from datetime import datetime
from .template import IEEETemplate


class ReportGenerator:
    """Generates Markdown reports of paper analysis."""

    def generate_report(
        self,
        file_path: str,
        sections: Dict[str, str],
        comparison: Dict,
        evaluation: Dict,
        template: IEEETemplate
    ) -> str:
        """Generate comprehensive analysis report."""
        
        report = f"""# Research Paper Analysis Report

**File:** {file_path}  
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## Executive Summary

This report analyzes the research paper structure and compliance with IEEE standards.

- **Overall Compliance:** {comparison.get('compliance_percentage', 0)}%
- **Quality Score:** {evaluation.get('overall_score', 0)}/100
- **Sections Found:** {len(comparison.get('found_sections', []))}/{len(template.required_sections)} required

---

## Structure Analysis

### Found Sections
{self._format_sections_list(comparison.get('found_sections', []))}

### Missing Required Sections
{self._format_missing_sections(comparison.get('missing_required', []))}

### Missing Optional Sections
{self._format_missing_sections(comparison.get('missing_optional', []), optional=True)}

### Section Order Validation
{'✅ Valid' if comparison.get('section_order_valid', False) else '❌ Invalid - Sections not in recommended order'}

---

## Detailed Section Analysis

{self._format_detailed_sections(comparison.get('section_details', {}))}

---

## Quality Evaluation

### Readability
- **Score:** {evaluation['readability'].get('score', 0)}/100
- **Average Words per Sentence:** {evaluation['readability'].get('avg_words_per_sentence', 0)}
- **Average Words per Paragraph:** {evaluation['readability'].get('avg_words_per_paragraph', 0)}

### Completeness
- **Score:** {evaluation['completeness'].get('score', 0)}/100
- **Required Sections Found:** {evaluation['completeness'].get('required_sections_found', 0)}/{evaluation['completeness'].get('required_sections_total', 0)}

### Structure
- **Score:** {evaluation['structure'].get('score', 0)}/100
- **Total Sections:** {evaluation['structure'].get('section_count', 0)}
- **Average Section Length:** {evaluation['structure'].get('avg_section_length', 0)} words

### Content Quality
- **Score:** {evaluation['content_quality'].get('score', 0)}/100
- **Total Words:** {evaluation['content_quality'].get('total_words', 0)}
- **Technical Indicators Found:** {evaluation['content_quality'].get('technical_indicators_found', 0)}
- **Citations Found:** {evaluation['content_quality'].get('citations_found', 0)}

---

## Recommendations

### Priority Issues
{self._generate_recommendations(comparison, evaluation, template)}

---

## Next Steps

1. Address missing required sections
2. Ensure proper section ordering
3. Improve low-scoring areas
4. Validate content meets IEEE standards

---

*This report was generated by Research Paper Analyzer v1.0*
"""
        return report

    @staticmethod
    def _format_sections_list(sections):
        """Format list of sections."""
        if not sections:
            return "No sections found."
        return '\n'.join(f"- {s}" for s in sections)

    @staticmethod
    def _format_missing_sections(sections, optional=False):
        """Format list of missing sections."""
        if not sections:
            section_type = "Optional" if optional else "Required"
            return f"✅ No missing {section_type.lower()} sections"
        
        type_label = "Optional" if optional else "**Required**"
        return '\n'.join(f"- ❌ {s} ({type_label})" for s in sections)

    @staticmethod
    def _format_detailed_sections(section_details):
        """Format detailed section analysis."""
        if not section_details:
            return "No section details available."
        
        details = []
        for section_key, info in section_details.items():
            status = "✅" if info.get('meets_minimum', False) else "❌"
            details.append(f"""
### {info.get('name', section_key)} {status}
- **Type:** {info.get('type', 'Unknown')}
- **Word Count:** {info.get('word_count', 0)}
- **Meets Minimum:** {info.get('meets_minimum', False)}
- **Meets Maximum:** {info.get('meets_maximum', False)}
""")
        return '\n'.join(details)

    @staticmethod
    def _generate_recommendations(comparison, evaluation, template):
        """Generate recommendations based on analysis."""
        recommendations = []
        
        # Missing sections recommendations
        if comparison.get('missing_required'):
            recommendations.append(f"- Add {len(comparison['missing_required'])} missing required section(s)")
        
        # Quality score recommendations
        if evaluation['overall_score'] < 50:
            recommendations.append("- Overall quality is significantly below target - major revisions needed")
        elif evaluation['overall_score'] < 75:
            recommendations.append("- Consider improving readability and structure")
        
        # Completeness recommendations
        if evaluation['completeness']['score'] < 100:
            recommendations.append(f"- Ensure all required sections are present ({evaluation['completeness']['required_sections_found']}/{evaluation['completeness']['required_sections_total']})")
        
        # Order recommendations
        if not comparison.get('section_order_valid'):
            recommendations.append("- Reorganize sections to follow IEEE standard order")
        
        if not recommendations:
            recommendations.append("- Paper appears to meet most IEEE standards")
        
        return '\n'.join(recommendations)
